# Generated by Django 2.1 on 2018-09-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationslog',
            name='excecuted',
            field=models.BooleanField(default=False),
        ),
    ]
