# Generated by Django 2.1 on 2018-08-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerHighestPeak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peak', models.IntegerField(default=0)),
                ('peak_date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'cp_highest_peak',
            },
        ),
    ]
