# Generated by Django 2.1 on 2018-08-09 07:01

from django.db import migrations


def add_highest_peak_data(apps, schema_editor):
    hightest_peak = apps.get_model('main_api', 'ServerHighestPeak')
    hightest_peak.objects.create(
        peak=0
    )


class Migration(migrations.Migration):
    dependencies = [
        ('main_api', '0002_serverhighestpeak'),
    ]

    operations = [
        migrations.RunPython(add_highest_peak_data, reverse_code=migrations.RunPython.noop)
    ]
