# Generated by Django 2.1 on 2018-09-17 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_api', '0003_auto_20180809_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, verbose_name='Account balance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Master account')),
            ],
            options={
                'db_table': 'cp_user_profile',
            },
        ),
        migrations.AlterModelOptions(
            name='userverification',
            options={'verbose_name': 'E-Mail Verification', 'verbose_name_plural': 'E-Mail Verifications'},
        ),
        migrations.AlterField(
            model_name='userverification',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Is token available?'),
        ),
        migrations.AlterField(
            model_name='userverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL, verbose_name='Master account'),
        ),
    ]
